version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_list_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persiste los datos en un volumen

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: task_list_db

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"  # Cambia esto si tu frontend se ejecuta en un puerto diferente
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db  # Este es el nombre del servicio MySQL
      PMA_USER: myuser
      PMA_PASSWORD: mypassword

volumes:
  db_data:
